### ISSUE TITLE
Nečekané přerušení sériového překladu

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#35]
Snakemake občas z ničeho nic skončí uprostřed překladu chybou podobnou této:

```
47 of 193 steps (24%) done
rule song_tex:
    input: ./tp-songs/01_folk/Rangers____Inženýrská.tex, /home/vasek/misc/zpevniky/tp/pisnicky/Snakefile.TP2011
    output: cache.TP_zpevnik_2011/0_Rangers____Inženýrská.tex
48 of 193 steps (25%) done
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/snakemake/__init__.py", line 379, in snakemake
    greediness=greediness)
  File "/usr/lib/python3.3/site-packages/snakemake/workflow.py", line 427, in execute
    success = scheduler.schedule()
  File "/usr/lib/python3.3/site-packages/snakemake/scheduler.py", line 210, in schedule
    self.run(job)
  File "/usr/lib/python3.3/site-packages/snakemake/scheduler.py", line 222, in run
    error_callback=self._error)
  File "/usr/lib/python3.3/site-packages/snakemake/executors.py", line 209, in run
    job.prepare()
  File "/usr/lib/python3.3/site-packages/snakemake/jobs.py", line 221, in prepare
    logger.warning(
AttributeError: 'Logger' object has no attribute 'warning'
```

Při příštím spuštění doběhne stejný cíl normálně. Stává se mi to jen, když překládám několik cílů za sebou. Možná nějaké přetečení kapacity?

**Comment by karel-brinda** [comment]
Tohle je chyba Snakemaku. Zkus ho upgradovat (`pip install --upgrade  snakemake`). S podobným problémem jsem se setkával před několika měsíci, ale myslel jsem, že to už bylo opravené. Pokud se to bude objevovat i po upgradu, je to zralé na ticket pro Snakemake.

**Comment by vasekp** [comment]
Díky! Od upgrade se chyba ještě neprojevila. Ale už předtím byla poměrně sporadická. Jestli se ještě ukáže, pošlu na snakemake, tady zavírám.
